const Router = require('koa-router');
const register = require('../controller/registerController.js');
const login = require('../controller/loginController.js');
const check = require('../controller/checkController.js');
const equip = require('../controller/inputEquipController.js');
const getEquip = require('../controller/getEquipController.js');
const editEquip = require('../controller/editEquipController.js');
const addLab = require('../controller/addLabController.js');
const getLab = require('../controller/getLabController.js');
const editLab = require('../controller/editLabController.js');
const addPass = require('../controller/addPassageController.js');
const getPass = require('../controller/getPassageController.js');
const editPass = require('../controller/editPassageController.js');
const deletePass = require('../controller/deletePassageController.js');
const tip = require('../controller/tipController.js');
const postDoc = require('../controller/docUploadController.js');
const getDocs = require('../controller/getDocController.js');
const deleteDoc = require('../controller/deleteDocController.js');
const teacher = require('../controller/teacherController.js');
const getTeacher = require('../controller/getTeacherController.js');
const arrange = require('../controller/classArrangeController.js');
const exp = require('../controller/expController.js');
const getExp = require('../controller/getExpsController.js');
const student = require('../controller/studentController.js');
const report = require('../controller/reportController.js');
const opReport = require('../controller/opReportController.js');
const router = new Router();

const multer = require('koa-multer');
const upload = multer({ dest: 'uploads/' });

router.get('/register', register);
router.get('/login', login);
router.get('/check', check);
router.get('/equip', equip);
router.get('/getequip', getEquip);
router.get('/editequip', editEquip);
router.get('/addlab', addLab);
router.get('/getlab', getLab);
router.get('/editlab', editLab);
router.get('/addpass', addPass);
router.get('/getpass', getPass);
router.get('/editpass', editPass);
router.get('/dpass', deletePass);
router.get('/tip', tip);
router.post('/postdoc', upload.single('file'), postDoc);
router.get('/getdocs', getDocs);
router.get('/deletedoc', deleteDoc);
router.get('/teacher', teacher);
router.get('/getteacher', getTeacher);
router.get('/arrange', arrange);
router.post('/exp', upload.single('file'), exp);
router.get('/getexp', getExp);
router.get('/student', student);
router.post('/report', upload.single('file'), report);
router.get('/opreport', opReport);
module.exports = router;